# Generated by Django 4.2.2 on 2023-12-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_meadia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallinkaccessrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Social link_access request', 'verbose_name_plural': 'Social link access requests'},
        ),
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'ordering': ['-created_at'], 'verbose_name': 'Social meadia', 'verbose_name_plural': 'Social meadias'},
        ),
        migrations.AlterField(
            model_name='sociallinkaccessrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=10),
        ),
    ]
