# Generated by Django 5.2.4 on 2025-09-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='code',
            field=models.CharField(default='free', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
