# Generated by Django 5.2.4 on 2025-09-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_plan_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='receipt',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='code',
            field=models.CharField(help_text='Unique code for the plan', max_length=20, unique=True),
        ),
    ]
