# Generated by Django 4.2.2 on 2023-06-30 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='community',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='familydetails',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='occupation',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='religion',
            options={'ordering': ['created_at']},
        ),
    ]
