# Generated by Django 4.2.2 on 2023-06-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_address_options_alter_community_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_id',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
