# Generated by Django 4.2.2 on 2023-08-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_profile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='religion',
            name='description',
        ),
        migrations.RemoveField(
            model_name='religion',
            name='education',
        ),
        migrations.AddField(
            model_name='religion',
            name='code',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
