# Generated by Django 4.2.2 on 2023-08-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_preference_preferred_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
