# Generated by Django 4.2.2 on 2023-08-30 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_community_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.community'),
        ),
    ]
