# Generated by Django 4.2.2 on 2023-09-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_alter_profile_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='physical_status',
            field=models.CharField(blank=True, choices=[('normal_person', 'Normal Person'), ('deaf_or_dumb', 'Deaf/Dumb'), ('blind', 'Blind'), ('physically_challenged', 'Physically Challenged'), ('mentally_challenged', 'Mentally Challenged'), ('other_disablity', 'Other Disablity')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='complexion',
            field=models.CharField(blank=True, choices=[('very_fair', 'Very Fair'), ('fair', 'Fair'), ('wheatish', 'Wheatish'), ('dark', 'Dark')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
