# Generated by Django 4.2.2 on 2023-09-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_profile_is_locked_profile_marital_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_locked',
            new_name='is_locked_photos',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_locked_social_accounts',
            field=models.BooleanField(default=False),
        ),
    ]
