# Generated by Django 4.2.2 on 2024-08-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_alter_address_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
