# Generated by Django 5.2.4 on 2025-09-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_profilephotoviewrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('free', 'Free'), ('trial', 'Trial'), ('promotional', 'Promotional'), ('premium', 'Premium')], default='free', max_length=30),
        ),
    ]
