# Generated by Django 5.2.4 on 2025-09-07 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('profiles', '0018_profile_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='account_type',
        ),
        migrations.AddField(
            model_name='profile',
            name='account_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.plan'),
        ),
        migrations.AddField(
            model_name='profile',
            name='plan_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
