# Generated by Django 4.2.2 on 2024-07-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temp_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
