# Generated by Django 4.2.2 on 2024-07-05 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options_remove_user_temp_id_tempuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tempuser',
            options={'ordering': ['-id'], 'verbose_name': 'Temp User', 'verbose_name_plural': 'Temp Users'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='tempuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
